#!/usr/bin/env python3
"""Build an OVDB-readable SQLite copy of the Chinook database from chinookdb.com.

DALgo's SQLite adapter addresses records by an `id` column, which the upstream
Chinook tables do not have. This copies the source file, adds a stable text
`id` derived from each table's primary key (every original column is kept) and
can emit the strict OpenVaultDB manifest for the result. The logic mirrors
openvaultdb/cloud/server/prepare_fixture.py.

The one pin is fixtures/chinook/chinookdb.json (the chinookdb.com address, its
jsDelivr mirror and the SHA-256 of the database file, plus the upstream
revision it was built from); the source must match that SHA-256. Fetch it with
scripts/fetch-chinook.sh. Requires Python 3.10 or newer.

usage: prepare_chinook.py SOURCE.sqlite OUTPUT.sqlite [--manifest MANIFEST.yaml]
       prepare_chinook.py --pin url|mirror|sha256|revision
"""

from __future__ import annotations

import sys

if sys.version_info < (3, 10):
    raise SystemExit(f"prepare_chinook.py needs Python 3.10 or newer (found {sys.version.split()[0]})")

import hashlib
import json
import shutil
import sqlite3
from pathlib import Path

PIN_FILE = Path(__file__).resolve().parent.parent / "fixtures" / "chinook" / "chinookdb.json"


def pinned_database() -> dict:
    """The pin flattened to the names --pin accepts."""
    pin = json.loads(PIN_FILE.read_text())
    return {
        "url": pin["sqlite"]["url"],
        "mirror": pin["sqlite"]["mirrorUrl"],
        "sha256": pin["sqlite"]["sha256"],
        "revision": pin["upstream"]["revision"],
    }


def field_type(sql_type: str) -> str:
    kind = sql_type.upper()
    if "INT" in kind:
        return "integer"
    if any(token in kind for token in ("REAL", "FLOA", "DOUB", "DECIMAL", "NUMERIC")):
        return "number"
    return "string"


def main(source: Path, output: Path, manifest_path: Path | None) -> None:
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    pinned = pinned_database()["sha256"]
    if digest != pinned:
        raise SystemExit(f"{source}: SHA-256 {digest} is not the pinned Chinook file ({pinned}, see {PIN_FILE.name})")
    output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, output)
    connection = sqlite3.connect(output)
    manifest = [
        "# Generated by scripts/prepare_chinook.py from the pinned Chinook SQLite file.",
        "database: {id: chinook, schema_mode: strict}",
        f"storage: {{engine: sqlite, path: ../../.demo-data/{output.name}}}",
        "schemas:",
        "  collections:",
    ]
    try:
        tables = [row[0] for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )]
        if len(tables) != 11:
            raise SystemExit(f"expected 11 Chinook tables, got {len(tables)}")
        for table in tables:
            columns = list(connection.execute(f'PRAGMA table_info("{table}")'))
            primary_keys = [name for _, name, _, _, _, pk in sorted(columns, key=lambda c: c[5]) if pk]
            if not primary_keys:
                raise SystemExit(f"table {table} has no primary key")
            row_count = connection.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
            connection.execute(f'ALTER TABLE "{table}" ADD COLUMN id TEXT')
            key_expression = " || ',' || ".join(f'CAST("{key}" AS TEXT)' for key in primary_keys)
            connection.execute(f'UPDATE "{table}" SET id = {key_expression}')
            connection.execute(f'CREATE UNIQUE INDEX "ovdb_{table}_id" ON "{table}" (id)')
            if connection.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0] != row_count:
                raise SystemExit(f"row count changed for {table}")
            manifest.extend((f"    {table}:", "      fields:"))
            for _, name, sql_type, _, _, _ in columns:
                manifest.append(f"        {name}: {{type: {field_type(sql_type)}}}")
        connection.commit()
        if connection.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
            raise SystemExit("derived SQLite file failed integrity check")
    finally:
        connection.close()
    if manifest_path is not None:
        manifest_path.write_text("\n".join(manifest) + "\n")


if __name__ == "__main__":
    args = sys.argv[1:]
    if len(args) == 2 and args[0] == "--pin":
        if args[1] not in ("url", "mirror", "sha256", "revision"):
            raise SystemExit(__doc__)
        print(pinned_database()[args[1]])
        raise SystemExit(0)
    manifest = None
    if len(args) == 4 and args[2] == "--manifest":
        manifest = Path(args[3])
        args = args[:2]
    if len(args) != 2:
        raise SystemExit(__doc__)
    main(Path(args[0]), Path(args[1]), manifest)
